# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c83ddc687c43b9f791050e8576592ac899ecb8ce17f29880596f3c0adcdc7404c46028340403c38e1e69590ca9d8d914ab61eb866429bbd22535b008ad071e

test:
  secret_key_base: d57963290cf5d6b65bb0a253a714ff2ddedc6c392e93e87fe1d402e9fb246282733b42d974ec2ba0529e86176019101d8417a41b32a8a4fda7a9d1c8fbcc91f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
